/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as TodoRouteRouteImport } from './routes/todo.route'
import { Route as ManageRouteRouteImport } from './routes/manage.route'
import { Route as AuthRouteRouteImport } from './routes/auth.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodoIndexRouteImport } from './routes/todo/index'
import { Route as ManageIndexRouteImport } from './routes/manage/index'
import { Route as TodoPaymentHistoryRouteImport } from './routes/todo/payment-history'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as TodoIdIndexRouteImport } from './routes/todo/$id/index'
import { Route as ManageCreateIndexRouteImport } from './routes/manage/create/index'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoRouteRoute = TodoRouteRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRouteRoute = ManageRouteRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoIndexRoute = TodoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TodoRouteRoute,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRouteRoute,
} as any)
const TodoPaymentHistoryRoute = TodoPaymentHistoryRouteImport.update({
  id: '/payment-history',
  path: '/payment-history',
  getParentRoute: () => TodoRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const TodoIdIndexRoute = TodoIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => TodoRouteRoute,
} as any)
const ManageCreateIndexRoute = ManageCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => ManageRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/manage': typeof ManageRouteRouteWithChildren
  '/todo': typeof TodoRouteRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/todo/payment-history': typeof TodoPaymentHistoryRoute
  '/manage/': typeof ManageIndexRoute
  '/todo/': typeof TodoIndexRoute
  '/manage/create': typeof ManageCreateIndexRoute
  '/todo/$id': typeof TodoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/todo/payment-history': typeof TodoPaymentHistoryRoute
  '/manage': typeof ManageIndexRoute
  '/todo': typeof TodoIndexRoute
  '/manage/create': typeof ManageCreateIndexRoute
  '/todo/$id': typeof TodoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/manage': typeof ManageRouteRouteWithChildren
  '/todo': typeof TodoRouteRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/todo/payment-history': typeof TodoPaymentHistoryRoute
  '/manage/': typeof ManageIndexRoute
  '/todo/': typeof TodoIndexRoute
  '/manage/create/': typeof ManageCreateIndexRoute
  '/todo/$id/': typeof TodoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/manage'
    | '/todo'
    | '/not-found'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/todo/payment-history'
    | '/manage/'
    | '/todo/'
    | '/manage/create'
    | '/todo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/not-found'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/todo/payment-history'
    | '/manage'
    | '/todo'
    | '/manage/create'
    | '/todo/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/manage'
    | '/todo'
    | '/not-found'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/todo/payment-history'
    | '/manage/'
    | '/todo/'
    | '/manage/create/'
    | '/todo/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ManageRouteRoute: typeof ManageRouteRouteWithChildren
  TodoRouteRoute: typeof TodoRouteRouteWithChildren
  NotFoundRoute: typeof NotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo/': {
      id: '/todo/'
      path: '/'
      fullPath: '/todo/'
      preLoaderRoute: typeof TodoIndexRouteImport
      parentRoute: typeof TodoRouteRoute
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/todo/payment-history': {
      id: '/todo/payment-history'
      path: '/payment-history'
      fullPath: '/todo/payment-history'
      preLoaderRoute: typeof TodoPaymentHistoryRouteImport
      parentRoute: typeof TodoRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/todo/$id/': {
      id: '/todo/$id/'
      path: '/$id'
      fullPath: '/todo/$id'
      preLoaderRoute: typeof TodoIdIndexRouteImport
      parentRoute: typeof TodoRouteRoute
    }
    '/manage/create/': {
      id: '/manage/create/'
      path: '/create'
      fullPath: '/manage/create'
      preLoaderRoute: typeof ManageCreateIndexRouteImport
      parentRoute: typeof ManageRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ManageRouteRouteChildren {
  ManageIndexRoute: typeof ManageIndexRoute
  ManageCreateIndexRoute: typeof ManageCreateIndexRoute
}

const ManageRouteRouteChildren: ManageRouteRouteChildren = {
  ManageIndexRoute: ManageIndexRoute,
  ManageCreateIndexRoute: ManageCreateIndexRoute,
}

const ManageRouteRouteWithChildren = ManageRouteRoute._addFileChildren(
  ManageRouteRouteChildren,
)

interface TodoRouteRouteChildren {
  TodoPaymentHistoryRoute: typeof TodoPaymentHistoryRoute
  TodoIndexRoute: typeof TodoIndexRoute
  TodoIdIndexRoute: typeof TodoIdIndexRoute
}

const TodoRouteRouteChildren: TodoRouteRouteChildren = {
  TodoPaymentHistoryRoute: TodoPaymentHistoryRoute,
  TodoIndexRoute: TodoIndexRoute,
  TodoIdIndexRoute: TodoIdIndexRoute,
}

const TodoRouteRouteWithChildren = TodoRouteRoute._addFileChildren(
  TodoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ManageRouteRoute: ManageRouteRouteWithChildren,
  TodoRouteRoute: TodoRouteRouteWithChildren,
  NotFoundRoute: NotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
